# Generated by Django 3.0.7 on 2020-07-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bit', models.CharField(max_length=10, verbose_name='Разрядность ОС')),
            ],
            options={
                'verbose_name': 'Разрядность',
                'verbose_name_plural': 'Разрядность',
            },
        ),
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кластера')),
            ],
            options={
                'verbose_name': 'Кластер',
                'verbose_name_plural': 'Кластеры',
            },
        ),
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_cpu', models.PositiveSmallIntegerField(verbose_name='Количество процессоров на материнской плате')),
            ],
            options={
                'verbose_name': 'Количество процессоров',
                'verbose_name_plural': 'Количество процессоров',
            },
        ),
        migrations.CreateModel(
            name='FamilyOSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя семейства операциооной системы')),
            ],
            options={
                'verbose_name': 'Семейство',
                'verbose_name_plural': 'Семейство',
            },
        ),
        migrations.CreateModel(
            name='HostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название хоста')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес хоста')),
                ('description', models.CharField(max_length=500, verbose_name='Описание хоста')),
                ('cpu', models.CharField(max_length=50, verbose_name='Процессор')),
                ('raid_controller', models.BooleanField(default=False, verbose_name='RAID контроллер')),
                ('total_storage', models.PositiveSmallIntegerField(default=0, verbose_name='Общий объём накопителей')),
                ('free_storage', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Свободное место на накопители')),
                ('inv', models.CharField(default='-', max_length=50, verbose_name='Инвентарный номер')),
                ('memory', models.PositiveSmallIntegerField(verbose_name='Объём оперативной памяти в гигабайтах')),
                ('free_memory', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Свободный объём оперативной памяти')),
                ('amt_cpu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server_monit.CPUModel', verbose_name='Количество процессоров на материнской плате')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_monit.ClusterModel', verbose_name='Кластер')),
            ],
            options={
                'verbose_name': 'Хост',
                'verbose_name_plural': 'Хосты',
            },
        ),
        migrations.CreateModel(
            name='OSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=50, verbose_name='Назваание операционной системы')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_monit.CapacityModel', verbose_name='Разрядность ОС')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_monit.FamilyOSModel', verbose_name='Семейство операционной системы')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
            },
        ),
        migrations.CreateModel(
            name='RAIDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_raid', models.CharField(max_length=10, verbose_name='Тип RAID массива')),
            ],
            options={
                'verbose_name': 'RAID',
                'verbose_name_plural': 'RAIDs',
            },
        ),
        migrations.CreateModel(
            name='TypeStorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_storage', models.CharField(max_length=50, verbose_name='Тип накопителя')),
            ],
            options={
                'verbose_name': 'Тип накопителя',
                'verbose_name_plural': 'Типы накопителей',
            },
        ),
        migrations.CreateModel(
            name='VirtualModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название виртуального сервера')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес виртуального сервера')),
                ('description', models.CharField(max_length=500, verbose_name='Описание виртуального сервера')),
                ('cores', models.PositiveSmallIntegerField(verbose_name='Колличество ядер')),
                ('threads', models.PositiveSmallIntegerField(verbose_name='Колличество потоков')),
                ('memory', models.PositiveSmallIntegerField(verbose_name='Объём оперативной памяти в гигабайтах')),
                ('storage_size', models.PositiveSmallIntegerField(verbose_name='Объём накопителя в гигабайтах')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtuals', to='server_monit.HostModel', verbose_name='На каком хосте размещен')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_monit.OSModel', verbose_name='Операционная система')),
                ('type_raid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_monit.RAIDModel', verbose_name='Тип RAID массива')),
            ],
            options={
                'verbose_name': 'Виртуальный сервер',
                'verbose_name_plural': 'Виртуальные сервера',
            },
        ),
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель накопителя')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Инв. №')),
                ('size_storage', models.PositiveSmallIntegerField(verbose_name='Объём накопителя в гигабайтах')),
                ('date_install', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пометки')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='server_monit.HostModel', verbose_name='На каком хосте размещен')),
                ('raid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='server_monit.StorageModel', verbose_name='RAID массив')),
                ('type_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_monit.TypeStorageModel', verbose_name='Тип накопителя')),
            ],
            options={
                'verbose_name': 'Накопитель',
                'verbose_name_plural': 'Накопители',
            },
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_monit.OSModel', verbose_name='Операционная система'),
        ),
    ]
