# Generated by Django 3.0.7 on 2020-07-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemodel',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='serial',
            field=models.CharField(default='', max_length=50, verbose_name='s/n'),
        ),
    ]
