# Generated by Django 3.0.7 on 2020-07-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0003_auto_20200731_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemodel',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='s/n'),
        ),
    ]
