# Generated by Django 3.0.7 on 2020-08-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0005_auto_20200801_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='raid_controller',
            field=models.CharField(max_length=100, verbose_name='RAID контроллер'),
        ),
    ]
