# Generated by Django 3.0.7 on 2020-07-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0016_auto_20200712_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAIDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_raid', models.CharField(max_length=10, verbose_name='Тип RAID массива')),
            ],
            options={
                'verbose_name': 'RAID',
                'verbose_name_plural': 'RAIDs',
            },
        ),
        migrations.RemoveField(
            model_name='capacitymodel',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='capacitymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='familyosmodel',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='familyosmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='osmodel',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='osmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='typestoragemodel',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='typestoragemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='virtualmodel',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='virtualmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='free_memory',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Свободный объём оперативной памяти'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='free_storage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Свободный место на накопители'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='total_storage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Общий объём накопителей'),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Пометки'),
        ),
    ]
