# Generated by Django 3.0.7 on 2020-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0017_auto_20200722_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_cpu', models.PositiveSmallIntegerField(verbose_name='Количество процессоров на материнской плате')),
            ],
            options={
                'verbose_name': 'Количество процессоров',
                'verbose_name_plural': 'Количество процессоров',
            },
        ),
    ]
