# Generated by Django 3.0.7 on 2020-07-23 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0018_cpumodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmodel',
            name='amt_cpu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server_monit.CPUModel', verbose_name='Количество процессоров на материнской плате'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='server_monit.HostModel', verbose_name='Кластер'),
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='raid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server_monit.RAIDModel', verbose_name='Тип RAID массива'),
        ),
    ]
