# Generated by Django 3.0.7 on 2020-07-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0019_auto_20200723_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostmodel',
            name='amt_cpu',
        ),
    ]
