# Generated by Django 3.0.7 on 2020-07-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0021_hostmodel_amt_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название кластера')),
            ],
            options={
                'verbose_name': 'Кластер',
                'verbose_name_plural': 'Кластеры',
            },
        ),
        migrations.RemoveField(
            model_name='hostmodel',
            name='raid',
        ),
        migrations.AddField(
            model_name='hostmodel',
            name='raid_controller',
            field=models.BooleanField(default=False, verbose_name='RAID контроллер'),
        ),
        migrations.AddField(
            model_name='storagemodel',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='server_monit.StorageModel', verbose_name='RAID массив'),
        ),
        migrations.AddField(
            model_name='virtualmodel',
            name='type_raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_monit.RAIDModel', verbose_name='Тип RAID массива'),
        ),
    ]
