# Generated by Django 3.0.7 on 2020-07-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0022_auto_20200727_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server_monit.ClusterModel', verbose_name='Кластер'),
        ),
    ]
