# Generated by Django 3.0.7 on 2020-07-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_monit', '0023_auto_20200727_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='free_memory',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Свободный объём оперативной памяти'),
        ),
        migrations.AlterField(
            model_name='hostmodel',
            name='free_storage',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Свободное место на накопители'),
        ),
    ]
